// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Beat struct {
	ID         int32     `json:"id"`
	CreatorID  int32     `json:"creator_id"`
	Title      string    `json:"title"`
	Genre      string    `json:"genre"`
	Key        string    `json:"key"`
	Bpm        int16     `json:"bpm"`
	Tags       string    `json:"tags"`
	S3Key      string    `json:"s3_key"`
	LikesCount int64     `json:"likes_count"`
	CreatedAt  time.Time `json:"created_at"`
}

type Like struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
	BeatID int32 `json:"beat_id"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}
