// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateBeat(ctx context.Context, arg CreateBeatParams) (Beat, error)
	CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBeat(ctx context.Context, id int32) error
	DeleteLike(ctx context.Context, arg DeleteLikeParams) error
	DeleteUser(ctx context.Context, id int32) error
	GetBeatById(ctx context.Context, id int32) (Beat, error)
	GetLikeByUserAndBeat(ctx context.Context, arg GetLikeByUserAndBeatParams) (Like, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListBeatsByBpmRange(ctx context.Context, arg ListBeatsByBpmRangeParams) ([]Beat, error)
	ListBeatsByCreatorId(ctx context.Context, arg ListBeatsByCreatorIdParams) ([]Beat, error)
	ListBeatsByCreatorIdAndBpmRange(ctx context.Context, arg ListBeatsByCreatorIdAndBpmRangeParams) ([]Beat, error)
	ListBeatsByCreatorIdAndGenre(ctx context.Context, arg ListBeatsByCreatorIdAndGenreParams) ([]Beat, error)
	ListBeatsByCreatorIdAndKey(ctx context.Context, arg ListBeatsByCreatorIdAndKeyParams) ([]Beat, error)
	ListBeatsByGenre(ctx context.Context, arg ListBeatsByGenreParams) ([]Beat, error)
	ListBeatsById(ctx context.Context, arg ListBeatsByIdParams) ([]Beat, error)
	ListBeatsByKey(ctx context.Context, arg ListBeatsByKeyParams) ([]Beat, error)
	ListLikesByBeat(ctx context.Context, arg ListLikesByBeatParams) ([]Like, error)
	ListLikesByUser(ctx context.Context, arg ListLikesByUserParams) ([]Like, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateBeat(ctx context.Context, arg UpdateBeatParams) (Beat, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
